name: GoldPriceBot

on:
  schedule:
    # اجرای دقیق بر اساس ساعت‌های داده شده
    - cron: "0 6 * * *"
    - cron: "0 8 * * *"
    - cron: "0 9 * * *"
    - cron: "0 10 * * *"
    - cron: "0 11 * * *"
    - cron: "30 11 * * *"
    - cron: "0 12 * * *"
    - cron: "0 13 * * *"
    - cron: "0 14 * * *"
    - cron: "0 15 * * *"
    - cron: "0 16 * * *"
    - cron: "0 17 * * *"
    - cron: "30 17 * * *"
    - cron: "0 18 * * *"
    - cron: "0 19 * * *"
    - cron: "0 20 * * *"
    - cron: "0 22 * * *"
    - cron: "0 0 * * *"
  # اجرای دستی برای تست
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver

      - name: Install Python dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install selenium requests

      - name: Run main.py
        run: python3 main.py
